entrada/urls.py
from django.urls import path
from .views import list_entrada, new_entrada, update_entrada, delete_entrada

app_name = 'entrada'
urlpatterns = [
    path('list_entrada/', list_entrada, name='list_entrada'),
    path('new_entrada/', new_entrada, name='new_entrada'),
    path('update_entrada/<int:pk>/', update_entrada, name='update_entrada'),
    path('delete_entrada/<int:pk>/', delete_entrada, name='delete_entrada'),
]

estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('produto/', include('produto.urls', namespace = 'produto')),
    path('entrada/', include('entrada.urls', namespace = 'entrada')),
    path('saida/', include('saida.urls', namespace = 'saida')),
    path('admin/', admin.site.urls),
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida

app_name = 'saida'
urlpatterns = [
    path('list_saida/', list_saida, name = 'list_saida'),
    path('new_saida/', new_saida, name = 'new_saida'),
    path('update_saida/<int:pk>/', update_saida, name = 'update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name = 'delete_saida'),
]

entrada/models.py
from django.db import models
from produto.models import Produtos

class Entradas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE, verbose_name='Produto')
    preco = models.FloatField('Preço', default=0)
    quantidade = models.IntegerField('Quantidade', default=0)
    criado = models.DateTimeField('Criado em', auto_now_add=True)
    modificado = models.DateTimeField('Modificado em', auto_now=True)

entrada/forms.py
from django.forms import ModelForm
from .models import Entradas

class EntradaForm(ModelForm):
    class Meta:
        model = Entradas
        fields = ['produto', 'quantidade', 'preco']

entrada/views.py
from django.shortcuts import render, redirect
from .models import Entradas
from .forms import EntradaForm

def list_entrada(request):
    entradas = Entradas.objects.all()
    template_name = 'list_entrada.html'
    context = {
        'entradas': entradas,
    }
    return render(request, template_name, context)

def new_entrada(request):
    if request.method == 'POST':
        form = EntradaForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade + form.cleaned_data['quantidade']
            form.cleaned_data['produto'].preco = form.cleaned_data['preco']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('entrada:list_entrada')
    else:
        template_name = 'new_entrada.html'
        context = {
            'form': EntradaForm(),
        }
        return render(request, template_name, context)

def update_entrada(request, pk):
    entrada = Entradas.objects.get(pk=pk)
    quantidade = entrada.quantidade
    print('==> ', quantidade)
    if request.method == 'POST':
        form = EntradaForm(request.POST, instance=entrada)
        if form.is_valid():
            print('===> ', quantidade, form.cleaned_data['quantidade'])
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - quantidade + form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('entrada:list_entrada')
    else:
        template_name = 'update_entrada.html'
        context = {
            'form': EntradaForm(instance = entrada),
            'pk': pk,
        }
        return render(request, template_name, context)

def delete_entrada(request, pk):
    entrada = Entradas.objects.get(pk=pk)
    entrada.produto.quantidade = entrada.produto.quantidade - entrada.quantidade
    entrada.produto.save()
    entrada.delete()
    return redirect('entrada:list_entrada')

entrada/templates/list_entrada.html
{% extends 'base.html' %}

{% block product %}

<h1><strong>Entradas</strong></h1><br>
<a class="button is-primary" href="{% url 'entrada:new_entrada' %}">Nova Entrada</a>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Preço</th>
            <th>Quantidade</th>
        </tr>
    </thead>
    <tbody>
        {% for entrada in entradas %}
        <tr>
            <th>{{ entrada.id }}</th>
            <td>{{ entrada.produto }}</td>
            <td>{{ entrada.preco }}</td>
            <td>{{ entrada.quantidade }}</td>
            <td><a class="button is-primary" href="{% url 'entrada:update_entrada' entrada.id %}">Alterar</a></td>
            <td><a class="button is-primary" href="{% url 'entrada:delete_entrada' entrada.id %}">Deletar</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

entrada/templates/new_entrada.html
{% extends 'base.html' %}

{% block product %}

<h1><strong>Nova Entrada</strong></h1><br>
<form action="{% url 'entrada:new_entrada' %}" method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <br><button class="button is-primary" type="submit">Salvar</button>
</form>

{% endblock %}

entrada/templates/update_entrada.html
{% extends 'base.html' %}

{% block product %}

<h1><strong>Alterar Entrada</strong></h1><br>
<form action="{% url 'entrada:update_entrada' pk %}" method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <br><button class="button is-primary" type="submit">Salvar</button> 
</form>

{% endblock %}