estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('produto/', include('produto.urls', namespace = 'produto')),
    path('entrada/', include('entrada.urls', namespace = 'entrada')),
    path('saida/', include('saida.urls', namespace = 'saida')),
    path('admin/', admin.site.urls),
]

produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto

app_name = 'produto'
urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto, name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto, name='delete_produto'),
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida

app_name = 'saida'
urlpatterns = [
    path('list_saida/', list_saida, name = 'list_saida'),
    path('new_saida/', new_saida, name = 'new_saida'),
    path('update_saida/<int:pk>/', update_saida, name = 'update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name = 'delete_saida'),
]

produto/models.py
from django.db import models

class Cores(models.Model):
    cor = models.CharField('Cor', max_length=200)
    
    def __str__(self):
        return self.cor
    
    class Meta:
        verbose_name = 'Cor'
        verbose_name_plural = 'Cores'
        ordering = ['cor']

class Produtos(models.Model):
    produto = models.CharField('Produto', max_length=200)
    cor = models.ForeignKey(Cores, on_delete=models.PROTECT,
    verbose_name='Cor')
    descricao = models.TextField('Descrição', blank=True)
    preco = models.DecimalField('Preço', decimal_places=2, max_digits=8, default=0)
    quantidade = models.IntegerField('Quantidade', default=0)
    criado = models.DateTimeField('Criado em', auto_now_add=True)
    modificado = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.produto

    def precoQuantidade(self):
        return self.preco * self.quantidade

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['-produto']

produto/forms.py
from django.forms import ModelForm
from .models import Produtos

class ProdutoForm(ModelForm):
    class Meta:
        model = Produtos
        fields = ['produto', 'cor', 'descricao']

produto/views.py
from django.shortcuts import render, redirect
from .models import Produtos
from .forms import ProdutoForm

def list_produto(request):
    produtos = Produtos.objects.all()
    template_name = 'list_produto.html'
    context = {
        'produtos': produtos,
    }
    return render(request, template_name, context)

def new_produto(request):
    if request.method == 'POST':
        form = ProdutoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('produto:list_produto')
    else:
        template_name = 'new_produto.html'
        context = {
            'form': ProdutoForm(),
        }
        return render(request, template_name, context)
        
def update_produto(request, pk):
    produto = Produtos.objects.get(pk=pk)
    if request.method == 'POST':
        form = ProdutoForm(request.POST, instance=produto)
        if form.is_valid():
            form.save()
            return redirect('produto:list_produto')
    else:
        template_name = 'update_produto.html'
        context = {
        'form': ProdutoForm(instance=produto),
        'pk': pk,
        }
        return render(request, template_name, context)

    
def delete_produto(request, pk):
    produto = Produtos.objects.get(pk=pk)
    produto.delete()
    return redirect('produto:list_produto')

produto/templates/list_produto.html
{% extends 'base.html' %}

{% block product %}

<h1><strong>Produtos</strong></h1><br>
<a class="button is-primary" href="{% url 'produto:new_produto' %}">Novo Produto</a>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Cor</th>
            <th>Preço</th>
            <th>Quantidade</th>
        </tr>
    </thead>
    <tbody>
        {% for produto in produtos %}
        <tr>
            <th>{{ produto.id }}</th>
            <td>{{ produto.produto }}</td>
            <td>{{ produto.cor }}</td>
            <td>{{ produto.preco }}</td>
            <td>{{ produto.quantidade }}</td>
            <td><a class="button is-primary" href="{% url 'produto:update_produto' produto.id %}">Alternar</a></td>
            <td><a class="button is-primary" href="{% url 'produto:delete_produto' produto.id %}">Deletar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

produto/templates/new_produto.html
{% extends 'base.html' %}

{% block product %}

<h1><strong>Novo Produto</strong></h1><br>
<form action="{% url 'produto:new_produto' %}" method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <br><button class="button is-primary" type="submit">Salvar</button>
</form>

{% endblock %}

produto/templates/update_produto.html
{% extends 'base.html' %}

{% block product %}

<h1><strong>Alterar Produto</strong></h1><br>
<form action="{% url 'produto:update_produto' pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <br><button class="button is-primary" type="submit">Salvar</button>
</form>

{% endblock %}