estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('produto/', include('produto.urls', namespace = 'produto')),
    path('entrada/', include('entrada.urls', namespace = 'entrada')),
    path('saida/', include('saida.urls', namespace = 'saida')),
    path('admin/', admin.site.urls),
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida

app_name = 'saida'
urlpatterns = [
    path('list_saida/', list_saida, name = 'list_saida'),
    path('new_saida/', new_saida, name = 'new_saida'),
    path('update_saida/<int:pk>/', update_saida, name = 'update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name = 'delete_saida'),
]

saida/models.py
from django.db import models
from produto.models import Produtos

class Saidas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE, verbose_name='Produto')
    preco = models.FloatField('Preço', default=0)
    quantidade = models.IntegerField('Quantidade', default=0)

saida/forms.py
from django.forms import ModelForm
from .models import Saidas

class SaidaForm(ModelForm):
    class Meta:
        model = Saidas
        fields = '__all__'

saida/views.py
from django.shortcuts import render, redirect
from .models import Saidas
from .forms import SaidaForm

def list_saida(request):
    saidas = Saidas.objects.all()
    template_name = 'list_saida.html'
    context = {
        'saidas': saidas,
    }
    return render(request, template_name, context)

def new_saida(request):
    if request.method == 'POST':
        form = SaidaForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].preco = form.cleaned_data['preco']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('saida:list_saida')
    else:
        template_name = 'new_saida.html'
        context = {
            'form': SaidaForm(),
        }
        return render(request, template_name, context)

def update_saida(request, pk):
    saida = Saidas.objects.get(pk=pk)
    quantidade = saida.quantidade
    print('==> ', quantidade)
    if request.method == 'POST':
        form = SaidaForm(request.POST, instance=saida)
        if form.is_valid():
            print('===> ', quantidade, form.cleaned_data['quantidade'])
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade + quantidade - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('saida:list_saida')
    else:
        template_name = 'update_saida.html'
        context = {
            'form': SaidaForm(instance = saida),
            'pk': pk,
        }
        return render(request, template_name, context)

def delete_saida(request, pk):
    saida = Saidas.objects.get(pk=pk)
    saida.produto.quantidade = saida.produto.quantidade + saida.quantidade
    saida.produto.save()
    saida.delete()
    return redirect('saida:list_saida')

saida/templates/list_saida.html
{% extends 'base.html' %}

{% block product %}

<h1><strong>Saídas</strong></h1><br>
<a class="button is-primary" href="{% url 'saida:new_saida' %}">Nova Saída</a>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Preço</th>
            <th>Quantidade</th>
        </tr>
    </thead>
    <tbody>
        {% for saida in saidas %}
        <tr>
            <th>{{ saida.id }}</th>
            <td>{{ saida.produto }}</td>
            <td>{{ saida.preco }}</td>
            <td>{{ saida.quantidade }}</td>
            <td><a class="button is-primary" href="{% url 'saida:update_saida' saida.id %}">Alterar</a></td>
            <td><a class="button is-primary" href="{% url 'saida:delete_saida' saida.id %}">Deletar</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

saida/templates/new_saida.html
{% extends 'base.html' %}

{% block product %}

<h1><strong>Nova Saída</strong></h1><br>
<form action="{% url 'saida:new_saida' %}" method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <br><button class="button is-primary" type="submit">Salvar</button>
</form>

{% endblock %}

saida/templates/update_saida.html
{% extends 'base.html' %}

{% block product %}

<h1><strong>Alterar Saída</strong></h1><br>
<form action="{% url 'saida:update_saida' pk %}" method = "post">
    {% csrf_token %}
    {{ form.as_p }}
    <br><button class="button is-primary" type="submit">Salvar</button> 
</form>

{% endblock %}